# Generated by Django 5.0.14 on 2026-02-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g2b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidannouncement',
            name='link_doc_no',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='연계문서번호값'),
        ),
        migrations.AlterField(
            model_name='bidannouncement',
            name='user_doc_no',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='이용자문서번호'),
        ),
        migrations.AlterField(
            model_name='bidcontract',
            name='user_doc_no',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='이용자문서번호'),
        ),
    ]
