# Generated by Django 5.0.14 on 2026-02-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g2b', '0002_widen_user_doc_no_link_doc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_ntce_no', models.CharField(max_length=40, verbose_name='입찰공고번호')),
                ('bid_ntce_ord', models.CharField(max_length=10, verbose_name='입찰공고차수')),
                ('openg_rank', models.CharField(blank=True, default='', max_length=10, verbose_name='개찰순위')),
                ('company_nm', models.CharField(blank=True, default='', max_length=100, verbose_name='대표업체')),
                ('company_bizno', models.CharField(blank=True, default='', max_length=20, verbose_name='대표업체사업자등록번호')),
                ('bid_class_no', models.CharField(blank=True, default='', max_length=10, verbose_name='입찰분류번호')),
                ('bid_progress_ord', models.CharField(blank=True, default='', max_length=10, verbose_name='입찰진행차수')),
                ('cntrct_req_no', models.CharField(blank=True, default='', max_length=40, verbose_name='계약요청접수번호')),
                ('cntrct_req_ord', models.CharField(blank=True, default='', max_length=10, verbose_name='계약요청접수차수')),
                ('user_doc_no', models.CharField(blank=True, default='', max_length=200, verbose_name='이용자문서번호')),
                ('detail_item_list', models.TextField(blank=True, default='', verbose_name='세부품명번호목록')),
                ('restrict_area_list', models.TextField(blank=True, default='', verbose_name='제한지역코드목록')),
                ('license_limit_list', models.TextField(blank=True, default='', verbose_name='면허업종제한목록')),
                ('item_class_no_list', models.TextField(blank=True, default='', verbose_name='물품분류번호목록')),
                ('eng_bid_ntce_nm', models.TextField(blank=True, default='', verbose_name='영문공고명')),
                ('construction_site_list', models.TextField(blank=True, default='', verbose_name='공사현장목록')),
                ('bid_ntce_nm', models.TextField(blank=True, default='', verbose_name='입찰공고명')),
                ('public_procurement_class', models.CharField(blank=True, default='', max_length=100, verbose_name='공공조달분류')),
                ('bid_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='투찰율')),
                ('success_lowest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='낙찰하한율')),
                ('base_amt', models.BigIntegerField(blank=True, null=True, verbose_name='기초금액')),
                ('total_assign_amt', models.BigIntegerField(blank=True, null=True, verbose_name='합계배정금액')),
                ('assign_budget_amt', models.BigIntegerField(blank=True, null=True, verbose_name='배정예산금액')),
                ('estimated_price', models.BigIntegerField(blank=True, null=True, verbose_name='예정가격')),
                ('bid_amt', models.BigIntegerField(blank=True, null=True, verbose_name='투찰금액')),
                ('bidder_cnt', models.IntegerField(blank=True, null=True, verbose_name='입찰참여자수')),
                ('presume_price', models.BigIntegerField(blank=True, null=True, verbose_name='입찰추정가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='적재일시')),
            ],
            options={
                'verbose_name': '입찰결과',
                'verbose_name_plural': '입찰결과',
                'indexes': [models.Index(fields=['company_bizno'], name='g2b_bidresu_company_a99325_idx'), models.Index(fields=['presume_price'], name='g2b_bidresu_presume_05767a_idx')],
                'unique_together': {('bid_ntce_no', 'bid_ntce_ord', 'company_bizno', 'bid_class_no', 'bid_progress_ord')},
            },
        ),
    ]
