# Generated by Django 5.0.14 on 2026-02-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g2b', '0003_add_bidresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidresult',
            name='bid_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='투찰율'),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='success_lowest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='낙찰하한율'),
        ),
    ]
