# Generated by Django 5.0.14 on 2026-03-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g2b', '0004_widen_bidresult_decimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidApiAValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_ntce_no', models.CharField(max_length=40, verbose_name='입찰공고번호')),
                ('bid_ntce_ord', models.CharField(max_length=10, verbose_name='입찰공고차수')),
                ('national_pension', models.BigIntegerField(default=0, verbose_name='국민연금')),
                ('health_insurance', models.BigIntegerField(default=0, verbose_name='건강보험')),
                ('retirement_mutual_aid', models.BigIntegerField(default=0, verbose_name='퇴직공제')),
                ('long_term_care', models.BigIntegerField(default=0, verbose_name='장기요양')),
                ('occupational_safety', models.BigIntegerField(default=0, verbose_name='산업안전')),
                ('safety_management', models.BigIntegerField(default=0, verbose_name='안전관리')),
                ('quality_management', models.BigIntegerField(default=0, verbose_name='품질관리')),
                ('price_decision_method', models.CharField(blank=True, default='', max_length=40, verbose_name='예정가격결정방식')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': 'API A값',
                'verbose_name_plural': 'API A값',
                'unique_together': {('bid_ntce_no', 'bid_ntce_ord')},
            },
        ),
        migrations.CreateModel(
            name='BidApiCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_ntce_no', models.CharField(max_length=40, verbose_name='입찰공고번호')),
                ('bid_ntce_ord', models.CharField(max_length=10, verbose_name='입찰공고차수')),
                ('a_value_status', models.CharField(choices=[('pending', '대기'), ('ok', '성공'), ('empty', '비대상'), ('error', '오류')], default='pending', max_length=20, verbose_name='A값 상태')),
                ('prelim_status', models.CharField(choices=[('pending', '대기'), ('ok', '성공'), ('empty', '비대상'), ('error', '오류')], default='pending', max_length=20, verbose_name='복수예비가격 상태')),
                ('error_detail', models.TextField(blank=True, default='', verbose_name='오류 상세')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'API 수집 로그',
                'verbose_name_plural': 'API 수집 로그',
                'indexes': [models.Index(fields=['a_value_status'], name='g2b_bidapic_a_value_f93b28_idx'), models.Index(fields=['prelim_status'], name='g2b_bidapic_prelim__1619ce_idx')],
                'unique_together': {('bid_ntce_no', 'bid_ntce_ord')},
            },
        ),
        migrations.CreateModel(
            name='BidApiPrelimPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_ntce_no', models.CharField(max_length=40, verbose_name='입찰공고번호')),
                ('bid_ntce_ord', models.CharField(max_length=10, verbose_name='입찰공고차수')),
                ('sequence_no', models.IntegerField(verbose_name='순번')),
                ('basis_planned_price', models.BigIntegerField(default=0, verbose_name='개별예비가격')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨여부')),
                ('draw_count', models.IntegerField(default=0, verbose_name='선택횟수')),
                ('planned_price', models.BigIntegerField(default=0, verbose_name='예정가격')),
                ('base_amount', models.BigIntegerField(default=0, verbose_name='기초금액')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': 'API 복수예비가격',
                'verbose_name_plural': 'API 복수예비가격',
                'unique_together': {('bid_ntce_no', 'bid_ntce_ord', 'sequence_no')},
            },
        ),
    ]
