# Generated by Django 6.0.2 on 2026-03-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g2b', '0005_bidapiavalue_bidapicollectionlog_bidapiprelimprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidannouncement',
            name='a_value_status',
            field=models.CharField(
                choices=[('pending', '미조회'), ('checked_missing', '조회-없음'), ('confirmed', '확인'), ('error', '재시도제외')],
                default='pending',
                help_text='confirmed=공식레코드확인, pending=미확인, checked_missing=조회했으나없음, error=재시도제외',
                max_length=20,
                verbose_name='A값 확정상태',
            ),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='base_amount_status',
            field=models.CharField(
                choices=[('pending', '미조회'), ('checked_missing', '조회-없음'), ('confirmed', '확인'), ('error', '재시도제외')],
                default='pending',
                help_text='confirmed=공식레코드확인, pending=미확인, checked_missing=조회했으나없음, error=재시도제외',
                max_length=20,
                verbose_name='기초금액 확정상태',
            ),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='a_value_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='A값 최종조회일시'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='base_amount_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='기초금액 최종조회일시'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='briefing_yn',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='설명회실시여부'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='briefing_date',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='설명회일자'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='briefing_time',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='설명회시각'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='industry_limit_yn',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='업종제한여부'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='region_limit_yn',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='지역제한여부'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='reserve_price_method',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='예정가격결정방법'),
        ),
        migrations.AddField(
            model_name='bidannouncement',
            name='bid_ntce_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='공고URL'),
        ),
    ]
